[package]
name = "my-http-server-swagger"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
quote = "*"
macros-utils = { version = "0.1.0", git = "https://github.com/MyJetTools/macros-utils.git" }
