mod model_reader;
mod read_body;
mod reading_from_header;
mod reading_from_path;
pub use model_reader::generate;
mod reading_query_string;
mod utils;
pub use reading_from_header::*;
pub use reading_from_path::*;
use reading_query_string::*;
